mod api;
mod auth;
mod permissions;

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use axum::{
    body::Body,
    extract::{DefaultBodyLimit, Request, State},
    http::{header, HeaderValue, Method, StatusCode, Uri},
    middleware::{self, Next},
    response::{IntoResponse, Response},
    routing::{delete, get, post, put},
    Router,
};
use clap::{Parser, Subcommand};
use rust_embed::RustEmbed;
use tower_cookies::CookieManagerLayer;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

use api::{
    auth_status, change_password_handler, collab_ws_handler, copy_entry, create_directory,
    create_file, create_user, delete_entry, delete_user, download_file, download_zip,
    events_ws_handler, get_settings, git_blame, git_branches, git_checkout, git_commit, git_diff,
    git_history, git_revert, git_stage, git_status, git_unstage, global_search, list_files,
    list_remotes, list_users, login_handler, logout_handler, read_file, rename_entry,
    save_settings, search_files, terminal_ws_handler, update_user, upload_file, upsert_remote,
    write_file, zip_extract_entry, zip_inspect, AppState,
};
use ferrite_core::Config;

#[derive(RustEmbed)]
#[folder = "../../frontend/"]
struct Assets;

#[derive(Parser)]
#[command(name = "ferrite")]
#[command(version = ferrum_core::FULL_VERSION_INFO)]
#[command(about = "Self-hosted remote file browser and editor")]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,

    #[arg(short, long, global = true, default_value = "ferrite.yaml")]
    config: PathBuf,

    #[arg(short, long, global = true, default_value = "127.0.0.1:8080")]
    bind: String,

    #[arg(long, global = true)]
    tls_cert: Option<PathBuf>,

    #[arg(long, global = true)]
    tls_key: Option<PathBuf>,
}

#[derive(Subcommand)]
enum Commands {
    Serve {
        #[arg(short, long, default_value = "ferrite.yaml")]
        config: PathBuf,

        #[arg(short, long, default_value = "127.0.0.1:8080")]
        bind: String,

        #[arg(long)]
        tls_cert: Option<PathBuf>,

        #[arg(long)]
        tls_key: Option<PathBuf>,
    },
    HashPassword {
        #[arg(help = "Plain text password to hash using Argon2id")]
        password: String,
    },
}

/// Written on first run when no config and no bundled example exist. Only the
/// local remote is enabled: every other entry is commented out so a fresh
/// install starts in a working state rather than pointing at invented servers
/// that will only ever fail to connect.
const DEFAULT_CONFIG: &str = r#"# Generated by Ferrite on first run. Edit freely.
# Full reference: ferrite/README.md

bind: "127.0.0.1:8080"

server_auth:
  enabled: false
  username: "admin"
  password_hash: ""          # generate with: ferrite hash-password
  totp_secret: null
  # secure_cookies: true     # set when a reverse proxy terminates TLS in front

tls:
  enabled: false
  cert_path: null
  key_path: null

limits:
  max_upload_mb: 50          # largest single upload or editor save

# trust_proxy_headers: true  # only behind a proxy that sets X-Forwarded-For

remotes:
  # Browse files on the machine Ferrite itself runs on. Needs no server, which
  # is why it is the only remote enabled by default.
  - name: this-pc
    protocol: local
    host: localhost
    port: 0
    username: local
    base_path: ""
    auth:
      password: ""

  # A Ferrous agent: the recommended way to reach a host you control, and the
  # only remote that also gives you a shell without an SSH server. Start the
  # agent, authorize the client key Ferrite prints at startup, then set
  # agent_pubkey to the agent's own key from its startup log. Pinning that key
  # is what makes a substituted agent fail instead of silently connecting.
  # - name: my-ferrous-host
  #   protocol: ferrous
  #   host: 127.0.0.1
  #   port: 9090
  #   username: local
  #   agent_pubkey: "<agent public key from the ferrous-agent startup log>"
  #   auth:
  #     password: ""

  # SFTP, against a reachable SSH server. Secrets may reference the
  # environment as ${VAR} so they never have to be written into this file.
  # - name: my-sftp-server
  #   protocol: sftp
  #   host: 192.168.1.100
  #   port: 22
  #   username: your-user
  #   auth:
  #     # Prefer key auth. private_key holds the path to the key file.
  #     private_key: "~/.ssh/id_ed25519"
  #     password: "${SFTP_PASSWORD}"

  # FTP.
  # - name: my-ftp-server
  #   protocol: ftp
  #   host: 192.168.1.200
  #   port: 21
  #   username: your-user
  #   auth:
  #     password: ""

# Which remote the interactive terminal opens. Deliberately left unset: with no
# terminal block Ferrite tells you none is configured, which is a better first
# run than dialling a server that was never there.
#
# Through a Ferrous agent. Needs allow_shell: true for this client in
# ferrous.yaml, and no SSH server anywhere:
# terminal:
#   name: terminal-ferrous
#   protocol: ferrous
#   host: 127.0.0.1
#   port: 9090
#   username: local
#   agent_pubkey: "<agent public key from the ferrous-agent startup log>"
#   auth:
#     password: ""
#
# Or over SSH, against a real SSH server:
# terminal:
#   name: terminal-ssh
#   protocol: sftp
#   host: 192.168.1.100
#   port: 22
#   username: your-user
#   auth:
#     private_key: "~/.ssh/id_ed25519"
"#;

/// Response headers every page and API reply carries.
///
/// The CSP allow-lists the two CDNs the editor and terminal load from (their
/// scripts are additionally pinned by integrity hashes in index.html) and
/// nothing else; `'unsafe-eval'` is required by Monaco's AMD loader.
async fn security_headers(State(hsts): State<bool>, req: Request, next: Next) -> Response {
    let mut response = next.run(req).await;
    let headers = response.headers_mut();
    headers.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'self'; \
             script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; \
             style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; \
             font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net data:; \
             img-src 'self' data: blob:; \
             media-src 'self' blob:; \
             connect-src 'self' ws: wss: https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; \
             worker-src 'self' blob: data:; \
             frame-ancestors 'none'; \
             base-uri 'self'; \
             form-action 'self'; \
             object-src 'none'",
        ),
    );
    headers.insert(header::X_CONTENT_TYPE_OPTIONS, HeaderValue::from_static("nosniff"));
    headers.insert(header::X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
    headers.insert(header::REFERRER_POLICY, HeaderValue::from_static("no-referrer"));
    headers.insert(
        "permissions-policy",
        HeaderValue::from_static("camera=(), microphone=(), geolocation=(), payment=(), usb=()"),
    );
    if hsts {
        headers.insert(
            header::STRICT_TRANSPORT_SECURITY,
            HeaderValue::from_static("max-age=31536000; includeSubDomains"),
        );
    }
    response
}

/// The host part of an `Origin` header value, `scheme://host[:port]`.
fn origin_host(origin: &str) -> &str {
    origin.split("://").nth(1).unwrap_or(origin).trim_end_matches('/')
}

/// Refuses WebSocket upgrades and state-changing API calls whose `Origin`
/// is not this server. The session cookie is `SameSite=Lax`, which already
/// keeps it off cross-site POSTs and scripted socket opens in every current
/// browser; this makes the same rule explicit and independent of cookie
/// behaviour. Requests without an `Origin` (curl, same-origin GETs) are
/// untouched.
async fn same_origin_guard(State(trust_proxy): State<bool>, req: Request, next: Next) -> Response {
    let path = req.uri().path();
    let guarded = path.starts_with("/ws/")
        || (path.starts_with("/api/") && !matches!(*req.method(), Method::GET | Method::HEAD | Method::OPTIONS));
    if guarded {
        if let Some(origin) = req.headers().get(header::ORIGIN).and_then(|v| v.to_str().ok()) {
            let mut allowed: Vec<&str> = Vec::new();
            if let Some(host) = req.headers().get(header::HOST).and_then(|v| v.to_str().ok()) {
                allowed.push(host);
            }
            if trust_proxy {
                if let Some(fwd) = req.headers().get("x-forwarded-host").and_then(|v| v.to_str().ok()) {
                    allowed.extend(fwd.split(',').map(str::trim));
                }
            }
            let origin = origin_host(origin);
            if !allowed.iter().any(|h| h.eq_ignore_ascii_case(origin)) {
                tracing::warn!("Refusing cross-origin request to {} from origin {}", path, origin);
                return (StatusCode::FORBIDDEN, "cross-origin request refused").into_response();
            }
        }
    }
    next.run(req).await
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::registry()
        .with(tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()))
        .with(tracing_subscriber::fmt::layer())
        .init();

    let cli = Cli::parse();
    tracing::info!("Starting Ferrite {}", ferrum_core::FULL_VERSION_INFO);
    let (config_path, bind_addr, tls_cert, tls_key) = match cli.command {
        Some(Commands::Serve { config, bind, tls_cert, tls_key }) => (config, bind, tls_cert, tls_key),
        Some(Commands::HashPassword { password }) => {
            let hash = auth::hash_password(&password).expect("Failed to hash password");
            println!("Generated Argon2id Hash:\n{}", hash);
            return Ok(());
        }
        None => (cli.config, cli.bind, cli.tls_cert, cli.tls_key),
    };

    if !config_path.exists() {
        let example_path = PathBuf::from("config/ferrite.example.yaml");
        if example_path.exists() {
            tracing::info!("Configuration file {:?} not found. Creating default from config/ferrite.example.yaml", config_path);
            let _ = std::fs::copy(&example_path, &config_path);
        } else {
            tracing::info!("Configuration file {:?} not found. Generating default ferrite.yaml", config_path);
            let _ = std::fs::write(&config_path, DEFAULT_CONFIG);
        }
    }

    tracing::info!("Loading configuration from {:?}", config_path);
    let config = Config::load_from_file(&config_path)?;

    let identity_path = config_path.with_file_name("ferrite_identity.key");
    let client_keypair = ferrum_core::load_or_generate_keypair(&identity_path)?;
    tracing::info!(
        "Ferrite client identity public key (share with Ferrous agents you want to connect to): {}",
        ferrum_core::to_hex(&client_keypair.public)
    );

    let cert_file = tls_cert.or_else(|| config.tls.cert_path.as_ref().map(PathBuf::from));
    let key_file = tls_key.or_else(|| config.tls.key_path.as_ref().map(PathBuf::from));
    let tls = match (cert_file, key_file) {
        (Some(cert), Some(key)) => Some((cert, key)),
        _ => None,
    };

    let secure_cookies = config.server_auth.secure_cookies.unwrap_or(tls.is_some());
    if config.server_auth.enabled && !secure_cookies {
        tracing::warn!(
            "Login is enabled but the session cookie is not marked Secure. Fine on localhost or a VPN; \
             behind an HTTPS reverse proxy set server_auth.secure_cookies: true."
        );
    }
    let body_limit = config.limits.max_upload_bytes();
    let trust_proxy = config.trust_proxy_headers;
    tracing::info!("Request body limit: {} MiB", config.limits.max_upload_mb);

    let app_state = Arc::new(AppState::new(config, config_path.clone(), Arc::new(client_keypair), secure_cookies)?);

    let app = Router::new()
        .route("/api/auth/status", get(auth_status))
        .route("/api/auth/login", post(login_handler))
        .route("/api/auth/logout", post(logout_handler))
        .route("/api/settings", get(get_settings).post(save_settings))
        .route("/api/settings/password", post(change_password_handler))
        .route("/api/remotes", get(list_remotes).post(upsert_remote))
        .route("/api/users", get(list_users).post(create_user))
        .route("/api/users/:username", put(update_user).delete(delete_user))
        .route("/api/files", get(list_files))
        .route("/api/file", get(read_file).put(write_file).post(create_file))
        .route("/api/directory", post(create_directory))
        .route("/api/entry", delete(delete_entry))
        .route("/api/rename", post(rename_entry))
        .route("/api/copy", post(copy_entry))
        .route("/api/download", get(download_file))
        .route("/api/download/zip", post(download_zip))
        .route("/api/upload", post(upload_file))
        .route("/api/search", get(search_files))
        .route("/api/search/global", get(global_search))
        .route("/api/git/status", get(git_status))
        .route("/api/git/diff", get(git_diff))
        .route("/api/git/blame", get(git_blame))
        .route("/api/git/history", get(git_history))
        .route("/api/git/commit", post(git_commit))
        .route("/api/git/stage", post(git_stage))
        .route("/api/git/unstage", post(git_unstage))
        .route("/api/git/revert", post(git_revert))
        .route("/api/git/branches", get(git_branches))
        .route("/api/git/checkout", post(git_checkout))
        .route("/api/zip/inspect", get(zip_inspect))
        .route("/api/zip/extract", get(zip_extract_entry))
        .route("/ws/terminal", get(terminal_ws_handler))
        .route("/ws/collab", get(collab_ws_handler))
        .route("/ws/events", get(events_ws_handler))
        .fallback(static_handler)
        .layer(DefaultBodyLimit::max(body_limit))
        .layer(middleware::from_fn_with_state(tls.is_some(), security_headers))
        .layer(middleware::from_fn_with_state(trust_proxy, same_origin_guard))
        .layer(CookieManagerLayer::new())
        .with_state(app_state);

    let addr: SocketAddr = bind_addr.parse()?;
    // Handlers see the peer address (login rate limiting keys on it).
    let service = app.into_make_service_with_connect_info::<SocketAddr>();

    if let Some((cert, key)) = tls {
        serve_tls(addr, service, &cert, &key).await?;
    } else {
        tracing::info!("Ferrite server starting on http://{}", addr);
        let listener = tokio::net::TcpListener::bind(addr).await?;
        axum::serve(listener, service).await?;
    }

    Ok(())
}

async fn serve_tls(
    addr: SocketAddr,
    service: axum::extract::connect_info::IntoMakeServiceWithConnectInfo<Router, SocketAddr>,
    cert_path: &Path,
    key_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    use axum_server::tls_rustls::RustlsConfig;

    tracing::info!("Ferrite server starting with TLS on https://{}", addr);
    let rustls_config = RustlsConfig::from_pem_file(cert_path, key_path).await?;
    axum_server::bind_rustls(addr, rustls_config).serve(service).await?;
    Ok(())
}

async fn static_handler(uri: Uri) -> impl IntoResponse {
    let mut path = uri.path().trim_start_matches('/');
    if path.is_empty() {
        path = "index.html";
    }

    match Assets::get(path) {
        Some(content) => {
            let mime = mime_guess::from_path(path).first_or_octet_stream();
            Response::builder()
                .header(header::CONTENT_TYPE, mime.as_ref())
                .body(Body::from(content.data))
                .unwrap()
        }
        None => {
            if let Some(index_content) = Assets::get("index.html") {
                Response::builder()
                    .header(header::CONTENT_TYPE, "text/html; charset=utf-8")
                    .body(Body::from(index_content.data))
                    .unwrap()
            } else {
                Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from("404 Not Found"))
                    .unwrap()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn origin_host_strips_scheme_and_trailing_slash() {
        assert_eq!(origin_host("https://files.example.com"), "files.example.com");
        assert_eq!(origin_host("http://127.0.0.1:8080/"), "127.0.0.1:8080");
        assert_eq!(origin_host("null"), "null");
    }
}
